export const APP_SCHEMA_VERSION = 1;

// Keep each item to exactly one SQL statement. D1's prepared-statement API is
// used for runtime initialization; newline-delimited exec() is intentionally
// avoided because it can split multiline statements incorrectly.
export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS app_schema (
    version INTEGER PRIMARY KEY,
    applied_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS user_profile (
    user_id TEXT PRIMARY KEY,
    display_name TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS recovery_credential (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    key_hash TEXT NOT NULL,
    key_salt TEXT NOT NULL,
    created_at TEXT NOT NULL,
    rotated_at TEXT,
    used_at TEXT,
    revoked_at TEXT,
    UNIQUE(user_id),
    FOREIGN KEY (user_id) REFERENCES user_profile(user_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS registration_invite (
    id TEXT PRIMARY KEY,
    token_hash TEXT NOT NULL UNIQUE,
    created_by TEXT NOT NULL,
    label TEXT,
    expires_at TEXT NOT NULL,
    used_at TEXT,
    used_by TEXT,
    revoked_at TEXT,
    attempts INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS passkey_credential (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    credential_id TEXT NOT NULL UNIQUE,
    public_key TEXT NOT NULL,
    counter INTEGER NOT NULL DEFAULT 0,
    transports TEXT,
    device_type TEXT NOT NULL,
    backed_up INTEGER NOT NULL DEFAULT 0 CHECK (backed_up IN (0, 1)),
    aaguid TEXT,
    name TEXT,
    created_at TEXT NOT NULL,
    last_used_at TEXT,
    revoked_at TEXT,
    FOREIGN KEY (user_id) REFERENCES user_profile(user_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS session (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    expires_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    ip_hash TEXT,
    user_agent TEXT,
    revoked_at TEXT,
    FOREIGN KEY (user_id) REFERENCES user_profile(user_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS webauthn_challenge (
    id TEXT PRIMARY KEY,
    challenge TEXT NOT NULL UNIQUE,
    ceremony TEXT NOT NULL CHECK (ceremony IN ('register', 'authenticate', 'recover', 'add-passkey')),
    user_id TEXT,
    invite_id TEXT,
    recovery_credential_id TEXT,
    expected_origin TEXT NOT NULL,
    expected_rp_id TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    used_at TEXT,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS auth_rate_limit (
    key TEXT PRIMARY KEY,
    count INTEGER NOT NULL,
    window_started_at TEXT NOT NULL,
    expires_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS auth_consumption (
    id TEXT PRIMARY KEY,
    kind TEXT NOT NULL,
    user_id TEXT,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS book_work (
    id TEXT PRIMARY KEY,
    owner_user_id TEXT NOT NULL,
    title TEXT NOT NULL,
    subtitle TEXT,
    synopsis TEXT NOT NULL DEFAULT '',
    subjects_json TEXT NOT NULL DEFAULT '[]',
    provenance_json TEXT NOT NULL DEFAULT '{}',
    first_published_date TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (owner_user_id) REFERENCES user_profile(user_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS book_edition (
    id TEXT PRIMARY KEY,
    work_id TEXT NOT NULL,
    contributors_json TEXT NOT NULL DEFAULT '[]',
    isbn10 TEXT,
    isbn13 TEXT,
    publisher TEXT,
    published_date TEXT,
    language TEXT,
    page_count INTEGER,
    cover_url TEXT,
    source_ids_json TEXT NOT NULL DEFAULT '{}',
    provenance_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (work_id) REFERENCES book_work(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS library_entry (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    edition_id TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('read', 'reading', 'want-to-read')),
    favorite INTEGER NOT NULL DEFAULT 0 CHECK (favorite IN (0, 1)),
    started_at TEXT,
    finished_at TEXT,
    shelves_json TEXT NOT NULL DEFAULT '[]',
    source TEXT NOT NULL,
    source_record_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT,
    FOREIGN KEY (user_id) REFERENCES user_profile(user_id) ON DELETE CASCADE,
    FOREIGN KEY (edition_id) REFERENCES book_edition(id) ON DELETE RESTRICT
  )`,
  `CREATE TABLE IF NOT EXISTS review (
    id TEXT PRIMARY KEY,
    library_entry_id TEXT NOT NULL UNIQUE,
    rating INTEGER NOT NULL DEFAULT 0 CHECK (rating BETWEEN 0 AND 5),
    body TEXT NOT NULL DEFAULT '',
    spoiler INTEGER NOT NULL DEFAULT 0 CHECK (spoiler IN (0, 1)),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    user_edited_at TEXT,
    FOREIGN KEY (library_entry_id) REFERENCES library_entry(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS appearance (
    id TEXT PRIMARY KEY,
    library_entry_id TEXT NOT NULL UNIQUE,
    registry_version INTEGER NOT NULL,
    preset_id TEXT NOT NULL,
    construction_id TEXT NOT NULL,
    scene_id TEXT NOT NULL,
    page_id TEXT NOT NULL,
    font_id TEXT NOT NULL,
    accent TEXT NOT NULL,
    decorations_json TEXT NOT NULL DEFAULT '[]',
    cover_treatment_id TEXT NOT NULL,
    opened_background_id TEXT NOT NULL,
    user_overrides_json TEXT NOT NULL DEFAULT '[]',
    updated_at TEXT NOT NULL,
    FOREIGN KEY (library_entry_id) REFERENCES library_entry(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS genre_assignment (
    id TEXT PRIMARY KEY,
    work_id TEXT NOT NULL UNIQUE,
    primary_genre TEXT NOT NULL,
    facets_json TEXT NOT NULL DEFAULT '[]',
    confidence REAL NOT NULL DEFAULT 0,
    reasons_json TEXT NOT NULL DEFAULT '[]',
    source TEXT NOT NULL,
    user_locked INTEGER NOT NULL DEFAULT 0 CHECK (user_locked IN (0, 1)),
    updated_at TEXT NOT NULL,
    FOREIGN KEY (work_id) REFERENCES book_work(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS import_job (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    source TEXT NOT NULL,
    status TEXT NOT NULL,
    total_rows INTEGER NOT NULL DEFAULT 0,
    imported_rows INTEGER NOT NULL DEFAULT 0,
    skipped_rows INTEGER NOT NULL DEFAULT 0,
    conflict_rows INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    completed_at TEXT,
    undone_at TEXT,
    FOREIGN KEY (user_id) REFERENCES user_profile(user_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS import_row (
    id TEXT PRIMARY KEY,
    import_job_id TEXT NOT NULL,
    row_number INTEGER NOT NULL,
    fingerprint TEXT NOT NULL,
    source_record_id TEXT,
    normalized_json TEXT NOT NULL,
    status TEXT NOT NULL,
    library_entry_id TEXT,
    conflict_json TEXT,
    created_at TEXT NOT NULL,
    UNIQUE(import_job_id, row_number),
    FOREIGN KEY (import_job_id) REFERENCES import_job(id) ON DELETE CASCADE,
    FOREIGN KEY (library_entry_id) REFERENCES library_entry(id) ON DELETE SET NULL
  )`,
  `CREATE TABLE IF NOT EXISTS local_migration (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    device_fingerprint TEXT NOT NULL,
    payload_hash TEXT NOT NULL,
    imported_count INTEGER NOT NULL,
    confirmed_at TEXT NOT NULL,
    UNIQUE(user_id, device_fingerprint, payload_hash),
    FOREIGN KEY (user_id) REFERENCES user_profile(user_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS domain_transfer_token (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    target_origin TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    consumed_at TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user_profile(user_id) ON DELETE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS idx_book_edition_isbn13 ON book_edition(isbn13) WHERE isbn13 IS NOT NULL`,
  `CREATE INDEX IF NOT EXISTS idx_book_work_owner ON book_work(owner_user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_book_edition_work_id ON book_edition(work_id)`,
  `CREATE INDEX IF NOT EXISTS idx_library_entry_user_updated ON library_entry(user_id, updated_at) WHERE deleted_at IS NULL`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_library_source_record ON library_entry(user_id, source, source_record_id) WHERE source_record_id IS NOT NULL`,
  `CREATE INDEX IF NOT EXISTS idx_import_job_user_created ON import_job(user_id, created_at)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_import_row_user_fingerprint ON import_row(import_job_id, fingerprint)`,
  `CREATE INDEX IF NOT EXISTS idx_registration_invite_expiry ON registration_invite(expires_at) WHERE used_at IS NULL AND revoked_at IS NULL`,
  `CREATE INDEX IF NOT EXISTS idx_passkey_user ON passkey_credential(user_id) WHERE revoked_at IS NULL`,
  `CREATE INDEX IF NOT EXISTS idx_session_user_expiry ON session(user_id, expires_at) WHERE revoked_at IS NULL`,
  `CREATE INDEX IF NOT EXISTS idx_webauthn_challenge_expiry ON webauthn_challenge(expires_at) WHERE used_at IS NULL`,
  `CREATE INDEX IF NOT EXISTS idx_domain_transfer_expiry ON domain_transfer_token(expires_at) WHERE consumed_at IS NULL`,
] as const;
